### PR TITLE
chore: add lnd 0.9.1 (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by kilrau**
EDIT: `0.9.1` would randomly crash for me with `11/SEGV` (see below). I am back to `0.9.0` and things are stable again.

```
Mar 02 16:37:37 ABC systemd[1]: Starting LND Lightning Daemon...
Mar 02 16:37:37 ABC systemd[1]: Started LND Lightning Daemon.
Mar 02 18:37:13 ABC systemd[1]: lnd.service: Main process exited, code=killed, status=11/SEGV
Mar 02 18:37:13 ABC systemd[1]: lnd.service: Failed with result 'signal'.
Mar 02 18:38:13 ABC systemd[1]: lnd.service: Service RestartSec=1min expired, scheduling restart.
Mar 02 18:38:13 ABC systemd[1]: lnd.service: Scheduled restart job, restart counter is at 1.
Mar 02 18:38:13 ABC systemd[1]: Stopped LND Lightning Daemon.
Mar 02 18:38:13 ABC systemd[1]: Starting LND Lightning Daemon...
Mar 02 18:38:13 ABC systemd[1]: Started LND Lightning Daemon.
Mar 02 20:50:10 ABC systemd[1]: lnd.service: Main process exited, code=killed, status=11/SEGV
Mar 02 20:50:10 ABC systemd[1]: lnd.service: Failed with result 'signal'.
Mar 02 20:51:10 ABC systemd[1]: lnd.service: Service RestartSec=1min expired, scheduling restart.
Mar 02 20:51:10 ABC systemd[1]: lnd.service: Scheduled restart job, restart counter is at 2.
Mar 02 20:51:10 ABC systemd[1]: Stopped LND Lightning Daemon.
Mar 02 20:51:10 ABC systemd[1]: Starting LND Lightning Daemon...
Mar 02 20:51:10 ABC systemd[1]: Started LND Lightning Daemon.
Mar 02 21:27:11 ABC systemd[1]: lnd.service: Main process exited, code=killed, status=11/SEGV
Mar 02 21:27:11 ABC systemd[1]: lnd.service: Failed with result 'signal'.
Mar 02 21:28:11 ABC systemd[1]: lnd.service: Service RestartSec=1min expired, scheduling restart.
Mar 02 21:28:11 ABC systemd[1]: lnd.service: Scheduled restart job, restart counter is at 3.
Mar 02 21:28:11 ABC systemd[1]: Stopped LND Lightning Daemon.
Mar 02 21:28:11 ABC systemd[1]: Starting LND Lightning Daemon...
```

Since `11/SEGV` hints at a memory access violation and I can't be sure this to be specific to my environment, I think it's a good idea for others (@openoms @jlopp @saubyk @CandleHater @rootzoll) to test-run this and report back. Goes without saying: don't run on a production/routing node.

### CODE REVIEW

**Comment by openoms** [comment]
Hi, thanks for raising this.
Would not merge or suggest updating before I have tested on different nodes successfully.
Will let you know if I find similar problems and in that case need to let the lnd devs know as well.

Good thing that because this is not a major version update the database should not have changed, so you should be able to downgrade to v0.9.0 by running the update script.
Will help to rule out if it is a new problem on your node or it is reproducable.

**Comment by kilrau** [comment]
> Good thing that because this is not a major version update the database should not have changed, so you should be able to downgrade to v0.9.0 by running the update script.

That's how I did it.

**Comment by openoms** [comment]
I have updated two raspiblitz 1.4-s, bith RPi4 4GB + SSD, will monitor for a while.

How long after did you get the issue?

What hardware you were testing on?

**Comment by kilrau** [comment]
> How long after did you get the issue?

30 mins up to several hours. Seemingly random.

> What hardware you were testing on?

Raspiblitz 1.4 (release, many services activated: TOR, RTL, electrs, btcpay, explorer, loop, lnbits, lndmanage), RPi4 4GB + HDD.

**Comment by openoms** [comment]
Getting the same errors: 
```
$ sudo journalctl -u lnd
-- Logs begin at Thu 2020-03-05 17:20:01 GMT, end at Thu 2020-03-05 22:50:41 GMT. --
Mar 05 20:28:13 raspberrypi systemd[1]: lnd.service: Main process exited, code=killed, status=11/SEGV
Mar 05 20:28:13 raspberrypi systemd[1]: lnd.service: Failed with result 'signal'.
Mar 05 20:29:13 raspberrypi systemd[1]: lnd.service: Service RestartSec=1min expired, scheduling restart.
Mar 05 20:29:13 raspberrypi systemd[1]: lnd.service: Scheduled restart job, restart counter is at 2.
Mar 05 20:29:13 raspberrypi systemd[1]: Stopped LND Lightning Daemon.
Mar 05 20:29:13 raspberrypi systemd[1]: Starting LND Lightning Daemon...
Mar 05 20:29:13 raspberrypi systemd[1]: Started LND Lightning Daemon.
admin@raspberrypi:~ $ 
```

**Comment by openoms** [comment]
1 node crashed after ~10 h even if compiled on go 1.13.3.

**Comment by openoms** [comment]
Will close this as v0.9.2 is done now: https://github.com/openoms/lightning-node-management/tree/master/lnd.updates#update-lnd-to-v092-beta

Thank you for testing and reporting this issue!

**Pull request closed without merging**
